spring:
  h2:
    console:
      # H2 웹 콘솔 활성화
      enabled: true

  jpa:
    # 쿼리 출력
    show-sql: true
    properties:
      hibernate:
        # MySQL 쿼리로 수행하도록 지정 (결과 차이는 없다.)
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect